networks:
    webnet:
        driver: bridge
services:
    traefik:
        image: traefik:latest
        command:
            - "--log.level=INFO"
            - "--api.dashboard=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.le.acme.email=crowmagnumb@pm.me"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "letsencrypt:/letsencrypt"
        networks:
            - webnet
        restart: unless-stopped
    website:
        image: nginx:alpine
        volumes:
            - "./website:/usr/share/nginx/html:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.static.rule=Host(`crowmagnumb.net`)"
            - "traefik.http.routers.static.entrypoints=websecure"
            - "traefik.http.routers.static.tls=true"
            - "traefik.http.routers.static.tls.certresolver=le"
            # HTTP → HTTPS redirect
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.static-http.rule=Host(`crowmagnumb.net`)"
            - "traefik.http.routers.static-http.entrypoints=web"
            - "traefik.http.routers.static-http.middlewares=redirect-to-https"
        networks:
            - webnet
        restart: unless-stopped
    radicale:
        image: tomsquest/docker-radicale:latest
        expose:
            - "5232"
        environment:
            - RADICALE_CONFIG=/etc/radicale/config
        volumes:
            - "./radicale/config:/etc/radicale/config:ro"
            - "./radicale/users:/etc/radicale/users:ro"
            - "./radicale/data:/var/lib/radicale"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radicale.rule=Host(`radicale.crowmagnumb.net`)"
            - "traefik.http.routers.radicale.entrypoints=websecure"
            - "traefik.http.routers.radicale.tls=true"
            - "traefik.http.routers.radicale.tls.certresolver=le"
            - "traefik.http.services.radicale.loadbalancer.server.port=5232"
        networks:
            - webnet
        restart: unless-stopped
volumes:
    letsencrypt:
